### ISSUE TITLE
nuxt.config.ts not supported

### ISSUE THREAD

**Issue by mtltechtemp** [nuxt-community/nuxt-generate-cluster#18]
Can you add support for TypeScript based Nuxt project please?

**Comment by mtltechtemp** [comment]
ping @pimlie

**Comment by gekkedev** [comment]
This is highly confusing; if no config file gets loaded (for whichever reason), only the help is displayed:
https://github.com/nuxt-community/nuxt-generate-cluster/blob/62ee4f19f95cc17530f88266920de29d0dfb7724/bin/nuxt-generate.js#L100-L102
I had to guess that it was Typescript-related and dig around in the code to confirm the suspicion, only to find out that the option `--config-file` actually gets ignored. Since not finding the config file is an expected error, something more helpful than a tutorial should be echoed.
