### ISSUE TITLE
@nuxt/sitemap not supported?

### ISSUE THREAD

**Issue by midblue** [nuxt-community/nuxt-generate-cluster#20]
Hi! I'm using nuxt-generate-cluster to generate my static site (`nuxt-generate -b`).
Latest version of Nuxt, latest everything.
At the end of my generation, under normal circumstances (i.e. `nuxt generate`), my sitemap gets generated. Great!
However, with nuxt-generate-cluster, this doesn't seem to happen. Is there any way I can manually generate the sitemap, or add a hook the end of this other generate function?

nuxt.config.js:
```
...
modules: [
    'nuxt-i18n',
    '@nuxtjs/feed',
    '@nuxtjs/sitemap',
  ],
...
  generate: {
    dir: './docs',
    fallback: '404.html',
    workers: 4,
    workerConcurrency: 20,
    concurrency: 20,
    routes: () => {...}
  },
...
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-generate-cluster/issues/c11">#c11</a>)</em></sub></div>

**Comment by pimlie** [comment]
`@nuxt/sitemap` creates the sitemap in the `generate:done` hook. This is incompatible with nuxt-generate-cluster as the generate:done hook will be called for every batch that a worker completes. Also the route cache will be empty as the cache is filled on the master and the generate:done hook is called on the workers.

Untested, but ncg has a done hook you could maybe use to manually call the generate:done hook on the master. ~~Unfortunately this doesnt receive the nuxt instance, so you need to get that from a nuxt hook:~~ Since `v.2.7.0` the Nuxt instance is passed as second arg to the done method:
```
// nuxt.config.js
...
  generate: {
    done({ duration, errors, workerInfo }, nuxt) {
      nuxt.callHook('generate:done')
    }
  }
```

Its a bit hacky but it might just work ;)

**Comment by midblue** [comment]
I see! Thanks!

**Comment by sebbean** [comment]
@midblue would love to know if you got this working w/ relative ease!

thinking about using it on my app as well (3k+ pages, hitting time limit on netlify deploy)

**Comment by midblue** [comment]
I did! I literally did just what pimile said above and it works perfectly.

**Comment by pimlie** [comment]
Since v.2.7.0 the Nuxt instance is passed as second arg to the done method, no need for using a Nuxt hook to get the Nuxt instance anymore

**Comment by simplenotezy** [comment]
@sebbean pro tip: build locally, then use Netlify CLI to push your code; that way you don't need to bypass the build minutes.
